main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.sign_up, name='signup'),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.about, name='about'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.search, name='search'),
    path('/data', views.data, name='data'),
]

story_b2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story7', include('story7.urls')),
    path('story8', include('story8.urls')),
]

main/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story7/forms.py
from django.forms import ModelForm
from .models import Status

main/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

def home(request):
    return render(request, 'main/home.html')

def sign_up(request):
	if request.method == 'POST':
	    username = request.POST['username']
	    email = request.POST['email']
	    password = request.POST['password']
	    if User.objects.filter(username=username).exists():
	    	messages.error(request, 'Username is not available!')
	    else:
	    	user = User.objects.create_user(username, email, password)
	    	return redirect('/story8')

	return render(request, 'main/signup.html')

story7/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
	return render(request, 'about.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

def search(request):
	return render(request, 'search.html')

def data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q="+ request.GET['q']
    ret = requests.get(url)
    print(ret.content)
    data2 = json.loads(ret.content)
    return JsonResponse(data2, safe=False)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Alifah Azka Nisrina {% endblock %}

{% block content %}
{% include 'navbar.html' %}
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Poppins:300,400,500,700" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="lib/animate/animate.min.css" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="css/style.css" rel="stylesheet">

  <style>
    a:link {
color:#ffffff;
text-decoration:none;
}

a:hover {
columns: #333333;;
text-decoration : none;
}

a:visited {
color:#ffffff;
text-decoration : none;
}
  </style>
	<section id="hero">
		<div class="hero-container">
		  <h1>Hello! <br></h1>
      <h2>Welcome back to my website</h2>
      <table>
        <th>
          <a href="{% url 'story7:about' %}" class="btn-get-started">Story 7</a>
        </th>
        <th>
          <a href="{% url 'story8:search' %}" class="btn-get-started">Story 8</a>
        </th>
      </table>

    </div>

    <button class="theme ml-3 mb-3 fixed-bottom" id="button"><a href="http://alppw.herokuapp.com/">Another Story</a></button>

	  </section><!-- #hero -->
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 9 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section id="login" style="background-color:white">
  {% for message in messages %}
    <script>
      alert("{{ message }}")
    </script>
  {% endfor %}

  {% if user.is_authenticated %}
		<h2> Hi {{ user.username }}! </h2>
    <p> You have already logged in </p>
    <a href="{% url 'story_10:home' %}" class="btn btn-primary">Back to Home</a>
  {% else %}
    <div class="section-title"> Log In </div>

    <form action="" method="POST">
	    {% csrf_token %}
	    <table class="table my-3" style="width:50vw">
		    <tr>
		    	<colgroup>
	      	<col span="1" style="width: 30%;">
	       	<col span="1" style="width: 10%;">
	       	<col span="1" style="width: 60%;">

		      <td> Username </td>
		      <td> : </td>
		      <td> <input id="username" name="username" type="text" required> </td>
		    </tr>

		    <tr>
		      <td> Password </td>
		      <td> : </td>
		      <td> <input id="password" name="password" type="password" required> </td>
		    </tr>

		  </table>
		  <input type="submit" value="Log In" class="btn btn-primary" id="login">
	  </form>

	  <br>
	  <div> 
	  	Don't have an account? Sign up
    	<a href="{% url 'story_10:signup' %}"> here </a>
	  </div>
  {% endif %}
</section>
{% endblock %}

main/templates/main/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 9 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section id="signup" style="background-color:white">
	{% for message in messages %}
    <script>
      alert("{{ message }}")
    </script>
  {% endfor %}

  {% if user.is_authenticated %}
  	<h2> Hi {{ user.username }}! </h2>
    <p> You have already logged in </p>
    <p> Log Out to create a new account </p>
    <a href="{% url 'main:home' %}#hero" class="btn btn-primary">Back to Home</a>
    <a href="/admin/logout/?next=/story8" class="btn btn-primary">Log Out</a>
  {% else %}
    <div class="section-title "> Sign Up </div>

    <form action="" method="POST">
	    {% csrf_token %}
	    <table class="table my-3" style="width:50vw">
    		<colgroup>
      	<col span="1" style="width: 30%;">
       	<col span="1" style="width: 10%;">
       	<col span="1" style="width: 60%;">

		    <tr>
		      <td> Username </td>
		      <td> : </td>
		      <td> <input id="username" name="username" type="text" required> </td>
		    </tr>

		    <tr>
		      <td> Email </td>
		      <td> : </td>
		      <td> <input id="email" name="email" type="email" required> </td>
		    </tr>

		    <tr>
		      <td> Password </td>
		      <td> : </td>
		      <td> <input id="password" name="password" type="password" required> </td>
		    </tr>

		  </table>
		  <input type="submit" value="Sign Up" class="btn btn-primary" id="signup">
	  </form>
  {% endif %}
</section>
{% endblock %}

story7/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 7 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section class="normal">
  <div class="section-title"> <br><br> Story 7 </div>

  <div class="accordion-container">
    <div id="activity" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Current Activity
        <div>
          <button class="up"> ^ </button>
          <button class="down"> v </button>
        </div>
      </a>

      <div class="content">
        <p> I'm an undergraduater student of University of Indonesia, Faculty of Computer Science <br> 
          I'm a student of PPM Al Faqih Mandiri </p>
      </div>
    </div>

    <div id="experience" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Experience
        <div>
          <button class="up"> ^ </button>
          <button class="down"> v </button>
        </div>
      </a>

      <div class="content">
        <p> Since i was a college student, I've been a <br>
          Staff of Creativ Wisgan <br>
          Mentor OKK UI <br>
          Deputy Chair of Media DPM  <br>
          Staff Project BKUI </p>
      </div>
    </div>
    
    <div id="achievement" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Achievement
        <div>
          <button class="up"> ^ </button>
          <button class="down"> v </button>
        </div>
      </a>

      <div class="content">
        <p> Still trying </p>
      </div>
    </div>
    
    <div id="contact" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Hobbies
        <div>
          <button class="up"> ^ </button>
          <button class="down"> v </button>
        </div>
      </a>

      <div class="content">
        <p> Drawing, Painting, Journalling </p>
      </div>
    </div>
  </div>
  <button class="theme ml-3 mb-3 fixed-bottom background-color: #e3bab3;" id="button"> Change Theme </button>
</section>
{% endblock %}

{% block script %}  <script src="{% static 'js/accordion.js' %}"></script> {% endblock %}

story8/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 8 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<section id="hero">
    <div class="hero-contain">
        <h1><br><br><br></h1>
      <h1>Books Collection</h1>
  <h2>Serach your favorite book</h2>
  <table>
    <th>
        <input class = "placeholder" type="text" id="keyword" placeholder="masukkan kata kunci">
        <ol id = "daftar_isi"class= "flex-container"></ol>
    </th>
  </table>
</div>

  </section><!-- #hero -->

{% endblock %}
{% block script %}
<script type="text/javascript">
    $("#keyword").keyup(function(){
        var ketikan = $("#keyword").val();
        console.log(ketikan);
        //panggil menggunakan teknik AJAX
        $.ajax({
        url : '/story8/data?q='+ ketikan,
        success : function(data){
            var array_items = data.items;
            $('#daftar_isi').empty();
            var i;
            for (i = 0; i < array_items.length; i++) {
            var judul = array_items[i].volumeInfo.title;
            var gambar = array_items[i].volumeInfo.imageLinks.smallThumbnail
            $('#daftar_isi').append("<li>"+judul+ "<br><img src="+gambar+ "alt=not uploaded>" +"</li>")
            }
        } 
        });
    });
</script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/new-style.css' %}">
        {% block style %}{% endblock %}

        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Handlee&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Cookie&display=swap" rel="stylesheet"> 
        
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>
        {% block script %}{% endblock %}
    </body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<style>
body {
  margin: 0;
  font-size: 28px;
  font-family: Arial, Helvetica, sans-serif;
}

.header {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: center;
}

#bs-example {
  overflow: hidden;
  background-color: #EFACAC;
}

#bs-example a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

#bs-example a:hover {
  background-color: #ddd;
  color: #EFACAC;
}

#bs-example a.active {
  background-color: #8C9AB6;
  color: white;
}

.content {
  padding: 16px;
}

.sticky {
  position: fixed;
  top: 0;
  width: 100%;
}

.sticky + .content {
  padding-top: 60px;
}
</style>
</head>
<body>

  <div class="bs-example">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a href="#" class="navbar-brand">🐾</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="{% url 'main:home' %}#hero" class="nav-item nav-link active">Home</a>
                <a href="{% url 'story7:about' %}" class="nav-item nav-link">Story 7</a>
                <a href="{% url 'story8:search' %}" class="nav-item nav-link">Story 8</a>
            </div>
            {% if user.is_authenticated %}
            <form class="form-inline ml-auto">
              <a href="#" class="nav-item nav-link">Halo {{ request.user.username}} </a>
              <a href="/admin/logout/?next=/story8" class="nav-item nav-link">Logout</a>
            </form>
    
            {% else %}
            <form class="form-inline ml-auto">
              <a href="{% url 'main:signup' %}" class="nav-item nav-link">Register</a>
              <a href="/admin/login/?next=/story8" class="nav-item nav-link">Login</a>
            </form>

            {% endif %}

        </div>
    </nav>
</div>

<!-- <div id="navbar">
  <a class="active" href="{% url 'main:home' %}#hero">Home</a>
  <a href="{% url 'story7:about' %}">Story 7</a>
  <a href="{% url 'story8:search' %}">Story 8</a>
</div>


<script>
window.onscroll = function() {myFunction()};

var navbar = document.getElementById("navbar");
var sticky = navbar.offsetTop;

function myFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky")
  } else {
    navbar.classList.remove("sticky");
  }
}
</script> -->

</body>
</html>